name: modcrelib_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - blast
  - cd-hit=4.8.1
  - clustalo=1.2.4
  - clustalw=2.1
  - emboss=6.6.0
  - ghostscript=9.53.3
  - hmmer=3.3.2
  - dssp=3.1.4
  - meme
  - tmalign
  - mmseqs2
  - pip
  - pip:
    - numpy
    - pandas
    - scipy
    - biopython
    - weblogo
