import os, sys, re
import configparser
import copy
import optparse

# Get scripts path (i.e. ".") #
exe_path = os.path.abspath(os.path.dirname(__file__))
if os.path.exists(os.path.join(exe_path,"..","ModCRElib")):
   scripts_path = os.path.join(exe_path,"..")
elif os.path.exists(os.path.join(exe_path,"..","..","ModCRElib")):
   scripts_path = os.path.join(exe_path,"..","..")
elif os.path.exists(os.path.join(exe_path,"..","..","..","ModCRElib")):
   scripts_path = os.path.join(exe_path,"..","..","..")
else:
   scripts_path = os.path.join(exe_path)

config_path  = os.path.join(scripts_path,"ModCRElib","configure")


# Append scripts path to python path #
sys.path.append(scripts_path)

# Read configuration file #
config = configparser.ConfigParser()
config_file = os.path.join(config_path, "config.ini")
config.read(config_file)

# Imports my functions #
from ModCRElib.beans import functions

# Import my modules #
from ModCRElib.structure.protein import tmalign

#-------------#
# Options     #
#-------------#

def parse_options():
    """
    Parse command-line options for fold clustering via TM-align.

    How to run:
        python folds.py -i PDB_CHAIN --pdb PDB_DIR
            [--dummy DUMMY_DIR -o OUTPUT_DIR]

    Example:
        python folds.py -i 1a02_F --pdb pdb_data -o folds_out

    The parser configures:
        - Reference PDB chain to evaluate.
        - PDB workspace directory containing split structures.
        - Output and temporary directories used during TM-align runs.

    Args:
        None.

    Returns:
        optparse.Values: Parsed CLI options for fold-search execution.
    """

    parser = optparse.OptionParser("python folds.py -i INPUT_PDB_CHAIN -p PDB_DIR [--dummy DUMMY_DIR -o OUTPUT_DIR]")

    parser.add_option("--dummy", default="/tmp/", action="store", type="string", dest="dummy_dir", help="Dummy directory (default = /tmp/)", metavar="{directory}")
    parser.add_option("-i", action="store", type="string", dest="input_pdb_name_chain", help="Input PDB name and chain (e.g. chain \"F\" of PDB \"1A02\" would be \"1a02_F\")", metavar="{string}")
    parser.add_option("-o", default="./", action="store", type="string", dest="output_dir", help="Output directory (default = ./)", metavar="{directory}")
    parser.add_option("-p", "--pdb", action="store", type="string", dest="pdb_dir", help="PDB directory (i.e. from pdb.py)", metavar="{directory}")

    (options, args) = parser.parse_args()

    if options.input_pdb_name_chain is None or options.pdb_dir is None:
        parser.error("missing arguments: type option \"-h\" for help")

    return options

def get_fold(pdb_chain, pdb_dir, output_dir="./", dummy_dir="/tmp"):
    """
    Compute fold-compatible chains for one reference protein-DNA template.

    The function compares the input chain against all split protein chains in
    the PDB workspace using TM-align and keeps chains that pass the configured
    minimum TM-score threshold.

    Args:
        pdb_chain (str): Reference chain identifier in `PDB_CHAIN` format.
        pdb_dir (str): PDB workspace directory generated by `pdb.py`.
        output_dir (str, optional): Directory where the fold table is written.
        dummy_dir (str, optional): Temporary directory used by TM-align.

    Returns:
        None. A `{pdb_chain}.txt` fold-membership file is written to `output_dir`.
    """

    # Initialize #
    fold = []
    folds_file = os.path.join(output_dir, pdb_chain + ".txt")
    min_tm_score = float(config.get("Parameters", "min_tm_score"))

    # For each PDB chain file... #
    for pdb_file in sorted(os.listdir(os.path.join(pdb_dir, "split"))):
        # Skip if not PDB chain file #
        if not pdb_file.endswith(".pdb"): continue
        if "dna" in pdb_file: continue
        # Skip if does not interact with DNA #
        triads_file = os.path.join(pdb_dir, "triads", pdb_file[:-4] + ".txt")
        if not os.path.exists(triads_file): continue
        # Superimpose PDB file over PDB chain #
        tmalign_obj = tmalign.get_tmalign_obj(os.path.join(pdb_dir, "split", pdb_chain + ".pdb"), os.path.join(pdb_dir, "split", pdb_file),dummy_dir)
        if min_tm_score <= min(tmalign_obj.get_tm_scores()):
            fold.append((pdb_file[:-4], min(tmalign_obj.get_tm_scores())))
    # Write output #
    functions.write(folds_file, "#pdb_chain;tm-score")
    for pdb_chain, tm_score in fold:
        functions.write(folds_file, "%s;%s" % (pdb_chain, tm_score))

#-------------#
# Main        #
#-------------#

def main():
    """
    Run the command-line fold-detection workflow.

    Workflow:
        1. Parse runtime options and normalize input/output paths.
        2. Compare the input PDB chain against all split structures.
        3. Keep structures above the configured TM-score threshold.
        4. Write the fold-membership table to the output directory.

    Returns:
        None. The fold summary file is written in the output directory.
    """
    # Arguments & Options #
    options = parse_options()

    # Get TMalign object #
    get_fold(options.input_pdb_name_chain, os.path.abspath(options.pdb_dir), os.path.abspath(options.output_dir), os.path.abspath(options.dummy_dir))


if __name__ == "__main__":
    main()
